version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      expo:
        patterns:
          - "expo"
          - "expo-*"
          - "@expo/*"
      react-native:
        patterns:
          - "react-native"
          - "react-native-*"
      navigation:
        patterns:
          - "@react-navigation/*"
      tests:
        patterns:
          - "jest"
          - "jest-*"
          - "babel-jest"
          - "@testing-library/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
