// Product image mapping — emoji + background color for each product keyword.
// getProductImage(name) does a case/diacritic-insensitive match against PRODUCT_IMAGES,
// then falls back to CATEGORY_FALLBACKS, then to a letter-based emoji for visual variety.

export const PRODUCT_IMAGES = {
  // Boulangerie / Pain
  pain: { emoji: '🥖', bg: '#FEF3C7' },
  baguette: { emoji: '🥖', bg: '#FEF3C7' },
  brioche: { emoji: '🍞', bg: '#FEF3C7' },
  croissant: { emoji: '🥐', bg: '#FEF3C7' },
  'pain de mie': { emoji: '🍞', bg: '#FEF3C7' },
  tartine: { emoji: '🍞', bg: '#FEF3C7' },
  'pain complet': { emoji: '🍞', bg: '#FEF3C7' },
  farine: { emoji: '🌾', bg: '#FEF3C7' },
  levure: { emoji: '🌾', bg: '#FEF3C7' },
  cereale: { emoji: '🌾', bg: '#FEF3C7' },
  muesli: { emoji: '🌾', bg: '#FEF3C7' },
  // Fruits
  pomme: { emoji: '🍎', bg: '#FEE2E2' },
  banane: { emoji: '🍌', bg: '#FEF9C3' },
  orange: { emoji: '🍊', bg: '#FFEDD5' },
  citron: { emoji: '🍋', bg: '#FEF9C3' },
  raisin: { emoji: '🍇', bg: '#E9D5FF' },
  fraise: { emoji: '🍓', bg: '#FEE2E2' },
  cerise: { emoji: '🍒', bg: '#FEE2E2' },
  pasteque: { emoji: '🍉', bg: '#DCFCE7' },
  melon: { emoji: '🍈', bg: '#DCFCE7' },
  ananas: { emoji: '🍍', bg: '#FEF9C3' },
  mangue: { emoji: '🥭', bg: '#FFEDD5' },
  poire: { emoji: '🍐', bg: '#DCFCE7' },
  peche: { emoji: '🍑', bg: '#FFEDD5' },
  abricot: { emoji: '🍑', bg: '#FFEDD5' },
  kiwi: { emoji: '🥝', bg: '#DCFCE7' },
  coco: { emoji: '🥥', bg: '#F3F4F6' },
  fruit: { emoji: '🍎', bg: '#FEE2E2' },
  clementine: { emoji: '🍊', bg: '#FFEDD5' },
  mandarine: { emoji: '🍊', bg: '#FFEDD5' },
  pamplemousse: { emoji: '🍊', bg: '#FFEDD5' },
  litchi: { emoji: '🍇', bg: '#E9D5FF' },
  myrtille: { emoji: '🫐', bg: '#DBEAFE' },
  framboise: { emoji: '🍓', bg: '#FEE2E2' },
  groseille: { emoji: '🍓', bg: '#FEE2E2' },
  figue: { emoji: '🍇', bg: '#E9D5FF' },
  datte: { emoji: '🍇', bg: '#E9D5FF' },
  prune: { emoji: '🍑', bg: '#FFEDD5' },
  grenade: { emoji: '🍎', bg: '#FEE2E2' },
  // Légumes
  tomate: { emoji: '🍅', bg: '#FEE2E2' },
  carotte: { emoji: '🥕', bg: '#FFEDD5' },
  salade: { emoji: '🥗', bg: '#DCFCE7' },
  laitue: { emoji: '🥬', bg: '#DCFCE7' },
  'pomme de terre': { emoji: '🥔', bg: '#FEF3C7' },
  patate: { emoji: '🥔', bg: '#FEF3C7' },
  avocat: { emoji: '🥑', bg: '#DCFCE7' },
  champignon: { emoji: '🍄', bg: '#FEF3C7' },
  mais: { emoji: '🌽', bg: '#FEF9C3' },
  oignon: { emoji: '🧅', bg: '#FEF3C7' },
  ail: { emoji: '🧄', bg: '#F3F4F6' },
  courgette: { emoji: '🥒', bg: '#DCFCE7' },
  concombre: { emoji: '🥒', bg: '#DCFCE7' },
  poivron: { emoji: '🫑', bg: '#DCFCE7' },
  brocoli: { emoji: '🥦', bg: '#DCFCE7' },
  chou: { emoji: '🥬', bg: '#DCFCE7' },
  epinard: { emoji: '🥬', bg: '#DCFCE7' },
  haricot: { emoji: '🫘', bg: '#DCFCE7' },
  'haricot vert': { emoji: '🫘', bg: '#DCFCE7' },
  lentille: { emoji: '🫘', bg: '#FEF3C7' },
  'pois chiche': { emoji: '🫘', bg: '#FEF3C7' },
  'petit pois': { emoji: '🫛', bg: '#DCFCE7' },
  betterave: { emoji: '🥕', bg: '#FEE2E2' },
  radis: { emoji: '🥕', bg: '#FEE2E2' },
  celeri: { emoji: '🥬', bg: '#DCFCE7' },
  navet: { emoji: '🥔', bg: '#F3F4F6' },
  poireau: { emoji: '🥬', bg: '#DCFCE7' },
  fenouil: { emoji: '🥬', bg: '#DCFCE7' },
  artichaut: { emoji: '🥬', bg: '#DCFCE7' },
  asperge: { emoji: '🥬', bg: '#DCFCE7' },
  aubergine: { emoji: '🍆', bg: '#E9D5FF' },
  legume: { emoji: '🥬', bg: '#DCFCE7' },
  persil: { emoji: '🌿', bg: '#DCFCE7' },
  basilic: { emoji: '🌿', bg: '#DCFCE7' },
  menthe: { emoji: '🌿', bg: '#DCFCE7' },
  coriandre: { emoji: '🌿', bg: '#DCFCE7' },
  herbe: { emoji: '🌿', bg: '#DCFCE7' },
  gingembre: { emoji: '🫚', bg: '#FEF3C7' },
  olive: { emoji: '🫒', bg: '#DCFCE7' },
  // Viandes & Poissons
  poulet: { emoji: '🍗', bg: '#FFEDD5' },
  viande: { emoji: '🥩', bg: '#FEE2E2' },
  steak: { emoji: '🥩', bg: '#FEE2E2' },
  boeuf: { emoji: '🥩', bg: '#FEE2E2' },
  veau: { emoji: '🥩', bg: '#FEE2E2' },
  agneau: { emoji: '🥩', bg: '#FEE2E2' },
  porc: { emoji: '🥩', bg: '#FEE2E2' },
  dinde: { emoji: '🍗', bg: '#FFEDD5' },
  canard: { emoji: '🍗', bg: '#FFEDD5' },
  lapin: { emoji: '🍗', bg: '#FFEDD5' },
  jambon: { emoji: '🥓', bg: '#FEE2E2' },
  saucisse: { emoji: '🌭', bg: '#FEE2E2' },
  saucisson: { emoji: '🌭', bg: '#FEE2E2' },
  merguez: { emoji: '🌭', bg: '#FEE2E2' },
  lardon: { emoji: '🥓', bg: '#FEE2E2' },
  bacon: { emoji: '🥓', bg: '#FEE2E2' },
  charcuterie: { emoji: '🥓', bg: '#FEE2E2' },
  'foie gras': { emoji: '🍖', bg: '#FEE2E2' },
  poisson: { emoji: '🐟', bg: '#DBEAFE' },
  saumon: { emoji: '🐟', bg: '#DBEAFE' },
  thon: { emoji: '🐟', bg: '#DBEAFE' },
  cabillaud: { emoji: '🐟', bg: '#DBEAFE' },
  sardine: { emoji: '🐟', bg: '#DBEAFE' },
  truite: { emoji: '🐟', bg: '#DBEAFE' },
  crevette: { emoji: '🦐', bg: '#FEE2E2' },
  huitre: { emoji: '🦪', bg: '#E0E7FF' },
  moule: { emoji: '🦪', bg: '#E0E7FF' },
  'fruit de mer': { emoji: '🦐', bg: '#DBEAFE' },
  crabe: { emoji: '🦀', bg: '#FEE2E2' },
  homard: { emoji: '🦞', bg: '#FEE2E2' },
  // Produits laitiers
  yaourt: { emoji: '🥛', bg: '#EFF6FF' },
  lait: { emoji: '🥛', bg: '#EFF6FF' },
  fromage: { emoji: '🧀', bg: '#FEF9C3' },
  beurre: { emoji: '🧈', bg: '#FEF9C3' },
  creme: { emoji: '🥛', bg: '#EFF6FF' },
  oeuf: { emoji: '🥚', bg: '#FEF3C7' },
  compote: { emoji: '🍎', bg: '#FEE2E2' },
  mozzarella: { emoji: '🧀', bg: '#FEF9C3' },
  camembert: { emoji: '🧀', bg: '#FEF9C3' },
  gruyere: { emoji: '🧀', bg: '#FEF9C3' },
  emmental: { emoji: '🧀', bg: '#FEF9C3' },
  parmesan: { emoji: '🧀', bg: '#FEF9C3' },
  chevre: { emoji: '🧀', bg: '#FEF9C3' },
  roquefort: { emoji: '🧀', bg: '#FEF9C3' },
  // Féculents & Pâtes
  riz: { emoji: '🍚', bg: '#F3F4F6' },
  pate: { emoji: '🍝', bg: '#FEF3C7' },
  pasta: { emoji: '🍝', bg: '#FEF3C7' },
  spaghetti: { emoji: '🍝', bg: '#FEF3C7' },
  nouille: { emoji: '🍝', bg: '#FEF3C7' },
  couscous: { emoji: '🍚', bg: '#FEF3C7' },
  semoule: { emoji: '🍚', bg: '#FEF3C7' },
  quinoa: { emoji: '🍚', bg: '#FEF3C7' },
  boulgour: { emoji: '🍚', bg: '#FEF3C7' },
  // Boissons
  eau: { emoji: '💧', bg: '#DBEAFE' },
  jus: { emoji: '🧃', bg: '#FFEDD5' },
  cafe: { emoji: '☕', bg: '#FEF3C7' },
  the: { emoji: '🍵', bg: '#DCFCE7' },
  tisane: { emoji: '🍵', bg: '#DCFCE7' },
  soda: { emoji: '🥤', bg: '#DBEAFE' },
  coca: { emoji: '🥤', bg: '#FEE2E2' },
  limonade: { emoji: '🥤', bg: '#FEF9C3' },
  biere: { emoji: '🍺', bg: '#FEF9C3' },
  vin: { emoji: '🍷', bg: '#E9D5FF' },
  champagne: { emoji: '🍾', bg: '#FEF9C3' },
  whisky: { emoji: '🥃', bg: '#FEF3C7' },
  sirop: { emoji: '🧃', bg: '#FFEDD5' },
  boisson: { emoji: '🥤', bg: '#DBEAFE' },
  smoothie: { emoji: '🥤', bg: '#DCFCE7' },
  lemonade: { emoji: '🥤', bg: '#FEF9C3' },
  // Sucré / Snacks
  chocolat: { emoji: '🍫', bg: '#FEF3C7' },
  biscuit: { emoji: '🍪', bg: '#FEF3C7' },
  gateau: { emoji: '🎂', bg: '#FEE2E2' },
  tarte: { emoji: '🥧', bg: '#FEE2E2' },
  glace: { emoji: '🍦', bg: '#DBEAFE' },
  bonbon: { emoji: '🍬', bg: '#FEF9C3' },
  confiture: { emoji: '🍯', bg: '#FEE2E2' },
  miel: { emoji: '🍯', bg: '#FEF3C7' },
  sucre: { emoji: '🍬', bg: '#FEF9C3' },
  'pop corn': { emoji: '🍿', bg: '#FEF9C3' },
  popcorn: { emoji: '🍿', bg: '#FEF9C3' },
  chips: { emoji: '🍿', bg: '#FEF9C3' },
  cookie: { emoji: '🍪', bg: '#FEF3C7' },
  nutella: { emoji: '🍫', bg: '#FEF3C7' },
  cacao: { emoji: '🍫', bg: '#FEF3C7' },
  dessert: { emoji: '🍰', bg: '#FEE2E2' },
  crepe: { emoji: '🥞', bg: '#FEF3C7' },
  gaufre: { emoji: '🧇', bg: '#FEF3C7' },
  pancake: { emoji: '🥞', bg: '#FEF3C7' },
  macaron: { emoji: '🍪', bg: '#E9D5FF' },
  // Plats préparés
  pizza: { emoji: '🍕', bg: '#FEE2E2' },
  burger: { emoji: '🍔', bg: '#FEF3C7' },
  hamburger: { emoji: '🍔', bg: '#FEF3C7' },
  sandwich: { emoji: '🥪', bg: '#FEF3C7' },
  wrap: { emoji: '🌯', bg: '#DCFCE7' },
  kebab: { emoji: '🥙', bg: '#FEF3C7' },
  tacos: { emoji: '🌮', bg: '#FEF9C3' },
  sushi: { emoji: '🍣', bg: '#FEE2E2' },
  soupe: { emoji: '🥣', bg: '#FFEDD5' },
  quiche: { emoji: '🥧', bg: '#FEF3C7' },
  gratin: { emoji: '🥘', bg: '#FEF3C7' },
  lasagne: { emoji: '🍝', bg: '#FEE2E2' },
  ravioli: { emoji: '🥟', bg: '#FEF3C7' },
  'plat prepare': { emoji: '🍱', bg: '#FFEDD5' },
  conserve: { emoji: '🥫', bg: '#FEE2E2' },
  surgelé: { emoji: '🧊', bg: '#DBEAFE' },
  // Condiments & Épices
  huile: { emoji: '🫒', bg: '#FEF9C3' },
  vinaigre: { emoji: '🫒', bg: '#FEF9C3' },
  sel: { emoji: '🧂', bg: '#F3F4F6' },
  poivre: { emoji: '🧂', bg: '#F3F4F6' },
  moutarde: { emoji: '🟡', bg: '#FEF9C3' },
  ketchup: { emoji: '🍅', bg: '#FEE2E2' },
  mayonnaise: { emoji: '🥚', bg: '#FEF9C3' },
  sauce: { emoji: '🥫', bg: '#FEE2E2' },
  epice: { emoji: '🌶️', bg: '#FEE2E2' },
  piment: { emoji: '🌶️', bg: '#FEE2E2' },
  curry: { emoji: '🌶️', bg: '#FEF9C3' },
  paprika: { emoji: '🌶️', bg: '#FEE2E2' },
  cumin: { emoji: '🌶️', bg: '#FEF3C7' },
  // Hygiène & Maison
  savon: { emoji: '🧴', bg: '#DBEAFE' },
  shampoing: { emoji: '🧴', bg: '#DBEAFE' },
  shampooing: { emoji: '🧴', bg: '#DBEAFE' },
  dentifrice: { emoji: '🪥', bg: '#DBEAFE' },
  lessive: { emoji: '🧺', bg: '#DBEAFE' },
  papier: { emoji: '🧻', bg: '#F3F4F6' },
  mouchoir: { emoji: '🧻', bg: '#F3F4F6' },
  serviette: { emoji: '🧻', bg: '#F3F4F6' },
  sac: { emoji: '🛍️', bg: '#F3F4F6' },
  eponge: { emoji: '🧽', bg: '#FEF9C3' },
  // Bébé & Animaux
  couche: { emoji: '🍼', bg: '#EFF6FF' },
  biberon: { emoji: '🍼', bg: '#EFF6FF' },
  croquette: { emoji: '🐾', bg: '#FEF3C7' },
  litiere: { emoji: '🐱', bg: '#F3F4F6' },
};

export const DEFAULT_PRODUCT = { emoji: '🛒', bg: '#F3F4F6' };

export const CATEGORY_FALLBACKS = [
  { keywords: ['bio', 'organic', 'nature'], img: { emoji: '🌱', bg: '#DCFCE7' } },
  { keywords: ['surgele', 'congele', 'frozen'], img: { emoji: '🧊', bg: '#DBEAFE' } },
  { keywords: ['conserve', 'boite', 'bocal'], img: { emoji: '🥫', bg: '#FEE2E2' } },
  { keywords: ['drink', 'boisson', 'soda', 'jus'], img: { emoji: '🥤', bg: '#DBEAFE' } },
  { keywords: ['viande', 'meat', 'poulet', 'boeuf', 'porc'], img: { emoji: '🥩', bg: '#FEE2E2' } },
  { keywords: ['poisson', 'fish', 'mer'], img: { emoji: '🐟', bg: '#DBEAFE' } },
  { keywords: ['legume', 'vegetable', 'vert'], img: { emoji: '🥬', bg: '#DCFCE7' } },
  { keywords: ['fruit', 'jus'], img: { emoji: '🍎', bg: '#FEE2E2' } },
  {
    keywords: ['lait', 'creme', 'yaourt', 'fromage', 'dairy'],
    img: { emoji: '🥛', bg: '#EFF6FF' },
  },
  { keywords: ['pain', 'boulang', 'patisserie'], img: { emoji: '🥖', bg: '#FEF3C7' } },
  { keywords: ['gâteau', 'gateau', 'dessert', 'sucre'], img: { emoji: '🍰', bg: '#FEE2E2' } },
  {
    keywords: ['hygiene', 'soin', 'beaute', 'douche', 'bain'],
    img: { emoji: '🧴', bg: '#DBEAFE' },
  },
  { keywords: ['menag', 'nettoy', 'produit'], img: { emoji: '🧹', bg: '#DBEAFE' } },
];

const LETTER_EMOJIS = {
  a: '🅰️',
  b: '🅱️',
  c: '©️',
  d: '🔶',
  e: '📧',
  f: '🎏',
  g: '🟢',
  h: '♓',
  i: 'ℹ️',
  j: '🎷',
  k: '🪁',
  l: '🍋',
  m: 'Ⓜ️',
  n: '🔷',
  o: '⭕',
  p: '🅿️',
  q: '🔲',
  r: '®️',
  s: '💲',
  t: '✝️',
  u: '⛎',
  v: '✅',
  w: '〰️',
  x: '❌',
  y: '💹',
  z: '💤',
};

function stripDiacritics(s) {
  return String(s || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

export function getProductImage(name) {
  const n = stripDiacritics(name);
  // Try exact/substring match from PRODUCT_IMAGES
  for (const [key, val] of Object.entries(PRODUCT_IMAGES)) {
    const kn = key.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    if (n.includes(kn)) return val;
  }
  // Fallback: try category keywords
  for (const cat of CATEGORY_FALLBACKS) {
    for (const kw of cat.keywords) {
      const kwn = kw.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
      if (n.includes(kwn)) return cat.img;
    }
  }
  // Final fallback: pick an emoji based on first letter for visual variety
  const firstChar = n.charAt(0);
  if (LETTER_EMOJIS[firstChar]) return { emoji: LETTER_EMOJIS[firstChar], bg: '#F3F4F6' };
  return DEFAULT_PRODUCT;
}
